### ISSUE TITLE
some docs around what does and doesn't work from vue?

### ISSUE THREAD

**Issue by gregbenner** [nodegui/vue-nodegui#3]
Since I think setup() isn't a standard lifecycle hook maybe a brief description. Like it run before everything else, models are declared as let instances and returned? can they be const also? Are there computed properties?

**Comment by shubhamzanwar** [comment]
setup() is a standard way of initiating components with Vue3. Since vue-nodegui is powered with a vue3 renderer, I think users may have to refer to the vue3 docs for understanding setup.

But this is still a good issue. I will add a link to vue3 docs in vue-nodegui readme
